### ISSUE TITLE
cooking init vue无反应

### ISSUE THREAD

**Issue by Cacivy** [cookingjs/cooking-vue#1]
执行`cooking init vue`
[cooking] - 下载脚手架相关依赖
[cooking] - downloading 'slush-cooking-vue'
[cooking] - 脚手架安装成功

[cooking] - generator project
然后文件夹下没有任何反应

手动安装 npm install slush-cooking-vue报错

```
npm ERR! tar.unpack untar error C:\Users\Cacivy\AppData\Roaming\npm-cache\slush-cooking-vue\0.1.8\package.tgz
```

**Comment by QingWei-Li** [comment]
https://github.com/ElemeFE/cooking/issues/30
